### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jvcasillas** [jvcasillas/many_babies_stim#2]
Manipulate complexity

- Number of elements
- Size of elements
- Expectedness of elements (Regularity, e.g., missing a line, distance, tiltedness)

**Comment by jvcasillas** [comment]
- [x] Make low complex squares have edges and similar movement
- [x] Low complexity circles: Make inner big circle smaller and outer circle bigger
- [x] Get HTML color codes for grey background and contrastive color pairs
- [x] Calculate surface area of colors (should be similar across complexity, use photoshop)

**Comment by jvcasillas** [comment]
- [ ] remove alpha fade from circles (all)
- [ ] make circles bigger (so you cant tell they are circles)
- [ ] use rings (instead of small circles)
- [ ] make inner most circles hollow
- [ ] make static squares have edges at top
